import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const features = [
  ['▦', 'POS / Kasir', 'Transaksi cepat yang langsung terhubung dengan stok.'],
  ['◫', 'Produk & Stok', 'Pantau persediaan dan transfer antar cabang.'],
  ['↗', 'Penjualan', 'Lihat tren omzet dan transaksi lebih jelas.'],
  ['◌', 'Keuangan', 'Catat pemasukan, pengeluaran, kas, dan laba.'],
  ['♙', 'Pelanggan', 'Bangun relasi pelanggan dengan data rapi.'],
  ['◈', 'Supplier', 'Kelola pemasok dan pembelian dalam satu alur.'],
  ['♧', 'Karyawan', 'Atur akses sesuai peran dan tanggung jawab.'],
  ['⌁', 'Multi-Cabang', 'Kelola perusahaan, toko, dan cabang terpisah.'],
  ['▥', 'Laporan', 'Ubah data operasional menjadi insight.'],
  ['▤', 'Google Sheets', 'Sinkronkan data bisnis yang didukung.'],
];
const faqs = [
  ['Apa itu NIAGANTARA?', 'NIAGANTARA adalah Business Control Platform untuk mengelola operasional bisnis—mulai dari POS, penjualan, stok, keuangan, hingga laporan—dalam satu sistem terintegrasi.'],
  ['Apakah bisa digunakan untuk banyak cabang?', 'Bisa. Struktur Company, Store, dan Branch membantu pemilik mengelola banyak lokasi dengan akses dan data yang terisolasi.'],
  ['Apakah tersedia POS?', 'Ya. POS terintegrasi dengan produk, stok, riwayat transaksi, dan konteks cabang.'],
  ['Apakah mendukung Google Sheets?', 'Ya. Admin perusahaan dapat menghubungkan Google Sheets untuk sinkronisasi data bisnis yang didukung.'],
  ['Apakah tersedia aplikasi mobile?', 'Pengalaman mobile sedang disiapkan. Dashboard web tetap responsif untuk perangkat mobile.'],
  ['Bagaimana keamanan data?', 'NIAGANTARA menggunakan autentikasi, role-based access, tenant dan branch isolation, audit logging, security events, serta Row Level Security.'],
  ['Bagaimana cara memulai?', 'Buat akun, buat toko, tambahkan cabang dan produk, lalu mulai kelola transaksi serta operasional Anda.'],
];

function BrandLogo({ compact = false }: { compact?: boolean }) {
  return <a className="brand" href="/" aria-label="NIAGANTARA — Beranda"><span className="brand-mark" aria-hidden="true"><span>N</span><i /><b /><em /></span><span className="brand-copy"><strong>NIAGANTARA</strong>{!compact && <small>BUSINESS CONTROL PLATFORM</small>}</span></a>;
}
function Button({ children, secondary = false, href = '#kontak' }: { children: React.ReactNode; secondary?: boolean; href?: string }) { return <a className={`button${secondary ? ' button-secondary' : ''}`} href={href}>{children}<span>→</span></a>; }
function Icon({ children }: { children: React.ReactNode }) { return <span className="feature-icon" aria-hidden="true">{children}</span>; }

function Dashboard({ small = false }: { small?: boolean }) {
  return <div className={`dashboard${small ? ' dashboard-small' : ''}`} aria-label="Pratinjau dashboard NIAGANTARA"><div className="dash-top"><span>● ● ●</span><b>Overview⌄</b><small>Senin, 22 Agustus 2026</small><i>A</i></div><div className="dash-body"><aside><div className="mini-logo">N</div><a className="active">▦ <span>Overview</span></a><a>◫ <span>Penjualan</span></a><a>◌ <span>Keuangan</span></a><a>◈ <span>Produk & Stok</span></a><a>⌁ <span>Cabang</span></a></aside><div className="dash-content"><div className="dash-heading"><div><small>Selamat datang kembali, Andi</small><h3>Ringkasan bisnis</h3></div><button>7 hari terakhir⌄</button></div><div className="stat-row"><div><small>Total Penjualan</small><b>Rp 48.620.000</b><em>↗ 12,8%</em></div><div><small>Total Transaksi</small><b>1.248</b><em>↗ 8,4%</em></div><div><small>Total Produk</small><b>684</b><em>Aktif</em></div><div><small>Total Pelanggan</small><b>2.431</b><em>↗ 6,2%</em></div></div><div className="dash-grid"><div className="chart-card"><div className="card-title"><b>Grafik Penjualan</b><small>Penjualan <i>●</i> Laba</small></div><div className="chart"><svg viewBox="0 0 500 150" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#2563eb" stopOpacity=".25" /><stop offset="1" stopColor="#2563eb" stopOpacity="0" /></linearGradient></defs><path d="M0 120C45 112 55 84 90 104S137 74 174 90S222 48 259 70S302 38 342 55S385 20 420 35S465 13 500 18V150H0Z" fill="url(#fill)"/><path d="M0 120C45 112 55 84 90 104S137 74 174 90S222 48 259 70S302 38 342 55S385 20 420 35S465 13 500 18" fill="none" stroke="#2563eb" strokeWidth="3"/></svg></div><div className="axis"><span>15 Agu</span><span>17 Agu</span><span>19 Agu</span><span>21 Agu</span><span>22 Agu</span></div></div><div className="distribution"><div className="card-title"><b>Distribusi Penjualan</b><small>•••</small></div><div className="donut"><b>Rp 48,6M</b><small>Total</small></div><p><i className="blue-dot" /> Toko Pusat <b>52%</b></p><p><i className="cyan-dot" /> Cabang Selatan <b>28%</b></p><p><i className="purple-dot" /> Cabang Utara <b>20%</b></p></div></div><div className="dash-lower"><div><div className="card-title"><b>Aktivitas Terbaru</b><a href="#fitur">Lihat semua</a></div><p>↗ <span>Penjualan baru <b>#INV-2481</b><small>2 menit lalu</small></span><strong>+Rp 1.240.000</strong></p><p>◫ <span>Stok diperbarui <b>Kopi Arabika 1kg</b><small>18 menit lalu</small></span><strong>+120 unit</strong></p></div><div><div className="card-title"><b>Top Produk</b><small>•••</small></div><p><i className="product blue-bg">K</i><span><b>Kopi Arabika</b><small>342 terjual</small></span><strong>Rp 12,4M</strong></p><p><i className="product cyan-bg">S</i><span><b>Susu Oat Barista</b><small>218 terjual</small></span><strong>Rp 8,2M</strong></p></div></div></div></div></div>;
}

function PosPreview() { return <div className="pos-preview"><div className="pos-head"><BrandLogo compact /><span>Toko Pusat⌄</span><i>A</i></div><div className="pos-body"><div className="pos-products"><div className="pos-tabs"><b>Semua Produk</b><span>Minuman</span><span>Makanan</span></div><div className="search">⌕ Cari produk atau scan barcode...</div><div className="product-grid">{[['K','Kopi Arabika','Rp 42.000','blue-bg'],['O','Oat Latte','Rp 35.000','purple-bg'],['T','Teh Melati','Rp 18.000','cyan-bg'],['R','Roti Sourdough','Rp 28.000','orange-bg']].map(([letter,name,price,color]) => <div key={name}><i className={`product-image ${color}`}>{letter}</i><b>{name}</b><small>{price}</small></div>)}</div></div><div className="cart"><div className="card-title"><b>Pesanan #2481</b><small>Hapus</small></div><p><i className="product blue-bg">K</i><span><b>Kopi Arabika</b><small>1 × Rp 42.000</small></span><strong>Rp 42.000</strong></p><p><i className="product cyan-bg">T</i><span><b>Teh Melati</b><small>2 × Rp 18.000</small></span><strong>Rp 36.000</strong></p><div className="cart-total"><span>Subtotal</span><b>Rp 78.000</b></div><button>Bayar Rp 78.000 <span>→</span></button></div></div></div>; }
function InventoryPreview() { return <div className="inventory"><div className="inventory-heading"><div><small>Produk & Stok</small><h3>Daftar Produk</h3></div><button>+ Tambah Produk</button></div><div className="inventory-tools"><span>⌕ Cari produk...</span><button>Semua Kategori⌄</button><button>Filter ▾</button></div><div className="table-scroll"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Stok Saat Ini</th><th>Minimum Stok</th><th>Status</th></tr></thead><tbody>{[['K','Kopi Arabika 1kg','Biji Kopi','120','50','Stok aman','good'],['S','Susu Oat Barista','Susu & Creamer','24','30','Hampir habis','warn'],['T','Teh Melati Premium','Teh','86','25','Stok aman','good']].map(([letter,name,category,stock,min,status,kind]) => <tr key={name}><td><i className={`product table-product ${letter==='S'?'cyan-bg':letter==='T'?'purple-bg':'blue-bg'}`}>{letter}</i><b>{name}</b></td><td>{category}</td><td><strong>{stock}</strong> unit</td><td>{min} unit</td><td><span className={`status ${kind}`}>{status}</span></td></tr>)}</tbody></table></div></div>; }

function Home() {
  const [menu, setMenu] = useState(false); const [faq, setFaq] = useState(0); const close = () => setMenu(false);
  return <div className="site"><header className="navbar"><div className="container nav-inner"><BrandLogo /><nav className={menu ? 'nav-open' : ''}><a href="#beranda" onClick={close}>Beranda</a><a href="#fitur" onClick={close}>Fitur</a><a href="#solusi" onClick={close}>Solusi</a><a href="#harga" onClick={close}>Harga</a><a href="#tentang" onClick={close}>Tentang</a><a href="#faq" onClick={close}>FAQ</a><a href="#kontak" onClick={close}>Kontak</a></nav><div className="nav-actions"><a className="login" href="https://niagantara-app.pages.dev">Masuk</a><a className="nav-cta" href="#kontak">Coba Gratis <span>→</span></a></div><button className="menu" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Buka menu"><span /><span /><span /></button></div></header><main>
    <section id="beranda" className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><i /> PLATFORM OPERASIONAL BISNIS MODERN</div><h1>Semua Bisnis Anda<br /><span>Dalam Satu Kendali</span></h1><p>NIAGANTARA membantu Anda mengelola penjualan, POS, stok, keuangan, pelanggan, karyawan, cabang, dan laporan bisnis dalam satu platform terintegrasi.</p><div className="actions"><Button href="#kontak">Mulai Sekarang</Button><Button secondary href="#showcase">Lihat Demo <small>▶</small></Button></div><div className="trust"><span>✓ Multi-Cabang</span><span>✓ Realtime</span><span>✓ Aman</span><span>✓ Terintegrasi</span></div></div><div className="hero-visual"><div className="float sales"><i>↗</i><span><small>Penjualan hari ini</small><b>Rp 8.420.000</b></span><em>+12,8%</em></div><div className="float stock"><i>◫</i><span><small>Stok hampir habis</small><b>12 Produk</b></span><em>Perlu perhatian</em></div><Dashboard /></div></div></section>
    <section className="logo-strip"><div className="container"><span>DIRANCANG UNTUK OPERASIONAL YANG LEBIH TERKENDALI</span><div><b>POS</b><b>INVENTORY</b><b>FINANCE</b><b>REPORTING</b><b>GOOGLE SHEETS</b></div></div></section>
    <section id="fitur" className="section features"><div className="container"><Heading kicker="SATU EKOSISTEM, LEBIH SEDERHANA" title={<>Satu Platform untuk<br /><span>Operasional Bisnis Anda</span></>} text="Semua alat yang Anda butuhkan untuk menjalankan bisnis sehari-hari, terhubung dalam satu sumber data yang konsisten." /><div className="feature-grid">{features.map(([icon,title,text]) => <article className="feature-card" key={title}><Icon>{icon}</Icon><h3>{title}</h3><p>{text}</p><a href="#showcase">Pelajari lebih lanjut <span>↗</span></a></article>)}</div></div></section>
    <section id="showcase" className="section showcase"><div className="container"><Heading kicker="VISIBILITAS TANPA JEDA" title={<>Pantau Bisnis <span>Secara Realtime</span></>} text="Satu pandangan yang jelas untuk memahami apa yang terjadi di seluruh operasional Anda." /><Dashboard /></div></section>
    <section id="solusi" className="section solution"><div className="container split"><div><Kicker>TRANSAKSI LEBIH CEPAT</Kicker><h2>POS / Kasir<br /><span>Terintegrasi</span></h2><p>Berikan pengalaman transaksi yang cepat untuk tim Anda. Setiap penjualan langsung tercatat dan stok otomatis diperbarui.</p><ul><li>✓ Pencarian produk & barcode scanner</li><li>✓ Pembayaran dan catatan pesanan</li><li>✓ Riwayat transaksi yang mudah dicari</li><li>✓ Otomatis memperbarui stok per cabang</li></ul><Button href="#kontak">Kenali POS NIAGANTARA</Button></div><PosPreview /></div></section>
    <section className="section inventory-section"><div className="container split reverse"><InventoryPreview /><div><Kicker>DATA STOK YANG AKURAT</Kicker><h2>Stok Lebih<br /><span>Terkontrol</span></h2><p>Ketahui apa yang tersedia, apa yang perlu dipesan, dan bagaimana stok bergerak di setiap lokasi.</p><div className="pills"><span>Produk</span><span>Kategori</span><span>Stok masuk</span><span>Transfer antar cabang</span><span>Riwayat stok</span></div><a className="text-link" href="#kontak">Lihat solusi inventaris <span>→</span></a></div></div></section>
    <section id="tentang" className="section branches"><div className="container branch-grid"><div><Kicker>DIBUAT UNTUK BERTUMBUH</Kicker><h2>Kelola Banyak Cabang<br /><span>dari Satu Tempat</span></h2><p>Bangun struktur bisnis yang rapi. Pantau performa setiap lokasi tanpa mencampur data antar tenant atau cabang.</p><div className="hierarchy"><div className="hierarchy-card company">◆ <span><b>Company</b><small>PT Niagantara Indonesia</small></span></div><i /><div className="hierarchy-row"><div className="hierarchy-card">◈ <span><b>Store</b><small>Toko Pusat</small></span></div><div className="hierarchy-card">◈ <span><b>Store</b><small>Toko Selatan</small></span></div></div><p>⌁ Cabang Utama　　⌁ Cabang Barat　　⌁ Cabang Selatan</p></div></div><div className="orbit"><div className="orbit-ring" /><div className="orbit-ring inner" /><div className="orbit-center"><span className="brand-mark large"><span>N</span><i /><b /><em /></span><strong>NIAGANTARA</strong><small>ONE SOURCE OF TRUTH</small></div><div className="orbit-card one"><b>Rp 18,2M</b><small>Omzet bulan ini</small></div><div className="orbit-card two"><b>12</b><small>Cabang aktif</small></div><div className="orbit-card three"><b>2.431</b><small>Pelanggan</small></div></div></div></section>
    <section className="section finance"><div className="container"><Heading kicker="DARI DATA MENJADI ARAH" title={<>Data Bisnis Menjadi <span>Keputusan</span></>} text="Gunakan data yang sama untuk melihat omzet, laba, arus kas, dan performa cabang dengan lebih percaya diri." /><div className="finance-grid"><div className="finance-main"><small>Omzet bulan ini</small><b>Rp 128.420.000</b><em>↗ 18,4% vs bulan lalu</em><div className="bars">{[35,54,48,74,63,88,78,100].map((height,i) => <i key={i} style={{height: `${height}%`}} />)}</div></div><Metric icon="◌" name="Laba bersih" value="Rp 42.860.000" change="↗ 14,2%" /><Metric icon="↗" name="Pengeluaran" value="Rp 85.560.000" change="Bulan ini" /><div className="reports"><div className="card-title"><b>Laporan yang tersedia</b><small>•••</small></div><p>▰ Laporan Penjualan <b>↗</b></p><p>▰ Performa Produk <b>↗</b></p><p>▰ Performa Cabang <b>↗</b></p></div></div></div></section>
    <section className="section sheets"><div className="container sheets-grid"><div><Kicker>TERHUBUNG DENGAN ALUR KERJA ANDA</Kicker><h2>Terhubung dengan<br /><span>Google Sheets</span></h2><p>Sinkronkan data bisnis yang didukung ke Google Sheets untuk analisis dan pelaporan yang lebih fleksibel.</p><a className="text-link" href="#faq">Pelajari cara kerja integrasi <span>→</span></a></div><div className="sheets-card"><div className="sheets-head"><i>▤</i><span><b>Google Sheets</b><small>NIAGANTARA Reporting</small></span><em>● Terhubung</em></div><div className="sheet"><small>Q3_Business_Report　　•••</small><div>{['Tanggal','Penjualan','Laba','Cabang','22 Agu','Rp 8.420.000','Rp 2.840.000','Toko Pusat','21 Agu','Rp 7.980.000','Rp 2.510.000','Selatan'].map((x,i) => <span key={`${x}-${i}`}>{x}</span>)}</div></div><p className="sync">Sinkronisasi terakhir <b>Hari ini, 09:42 WIB</b><br />Sheet aktif <b>Q3_Business_Report</b></p></div></div></section>
    <section className="section security"><div className="container security-panel"><div><Kicker>DIBANGUN DENGAN KEPERCAYAAN</Kicker><h2>Keamanan untuk<br /><span>Data Bisnis Anda</span></h2><p>Kontrol yang tepat untuk menjaga data tetap aman, terpisah, dan dapat dipertanggungjawabkan.</p></div><div className="security-grid">{[['◆','Authentication','Akses akun yang terverifikasi'],['⌁','Tenant Isolation','Data antar perusahaan terpisah'],['♧','Role-based Access','Akses sesuai peran tim'],['▥','Audit Logging','Aktivitas tercatat dan dapat ditelusuri'],['◈','Branch Access Control','Kontrol akses per lokasi'],['ϟ','Security Events','Visibilitas kejadian keamanan']].map(([icon,title,text]) => <div key={title}><Icon>{icon}</Icon><span><b>{title}</b><small>{text}</small></span></div>)}</div></div></section>
    <section className="section mobile"><div className="container mobile-grid"><div><Kicker>FLEKSIBEL DI MANA SAJA</Kicker><h2>Kelola Bisnis<br /><span>di Mana Saja</span></h2><p>Dashboard yang mengikuti ritme kerja Anda—di meja kerja, di toko, atau saat bepergian.</p><ul><li>✓ Desktop dashboard</li><li>✓ Mobile-ready</li><li>✓ Satu identitas produk</li></ul></div><div className="devices"><div className="device-desktop"><Dashboard small /></div><div className="phone"><div className="phone-notch" /><small>Selamat datang, Andi</small><h4>Ringkasan bisnis</h4><div><small>Total Penjualan</small><b>Rp 48,62M</b><em>↗ 12,8%</em></div><div className="phone-bars">{[28,45,38,67,58,82,72].map((height,i) => <i key={i} style={{height: `${height}%`}} />)}</div><footer>⌂　 <b>▦</b>　◫　♙</footer></div></div></div></section>
    <section id="harga" className="section pricing"><div className="container"><Heading kicker="PILIH CARA ANDA BERTUMBUH" title={<>Harga yang <span>Transparan</span></>} text="Paket berlangganan sedang kami siapkan untuk kebutuhan bisnis yang berbeda." /><div className="price-grid"><Price name="FREE" title="Mulai mengenal NIAGANTARA" text="Untuk mencoba fondasi pengelolaan bisnis." /><Price featured name="BUSINESS" title="Operasional yang lebih terhubung" text="Untuk tim yang ingin bekerja dari satu sumber data." /><Price name="ENTERPRISE" title="Kontrol untuk skala yang lebih besar" text="Untuk organisasi dengan kebutuhan operasional khusus." /></div></div></section>
    <section className="section steps"><div className="container"><Heading kicker="MULAI DALAM EMPAT LANGKAH" title={<>Dari setup hingga <span>siap beroperasi</span></>} /><div className="step-grid">{[['01','♙','Buat Akun','Daftarkan bisnis dan akun administrator Anda.'],['02','⌁','Buat Toko','Tentukan struktur toko pusat operasional.'],['03','◫','Tambah Cabang & Produk','Bangun katalog dan lokasi bisnis Anda.'],['04','ϟ','Mulai Kelola Bisnis','Jalankan operasional dengan visibilitas lebih baik.']].map(([number,icon,title,text]) => <div key={number}><b>{number}</b><Icon>{icon}</Icon><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section id="faq" className="section faq"><div className="container faq-grid"><div><Kicker>PERTANYAAN UMUM</Kicker><h2>Punya <span>pertanyaan?</span></h2><p>Jika belum menemukan jawaban yang Anda cari, hubungi tim kami.</p><a className="text-link" href="mailto:support@niagantara.com">Hubungi support <span>→</span></a></div><div>{faqs.map(([question,answer],i) => <div className={`faq-item${faq===i?' open':''}`} key={question}><button onClick={() => setFaq(faq===i?-1:i)} aria-expanded={faq===i}>{question}<i>{faq===i?'−':'+'}</i></button>{faq===i && <p>{answer}</p>}</div>)}</div></div></section>
    <section id="kontak" className="cta"><div className="container"><Kicker>SATU KENDALI UNTUK LANGKAH BERIKUTNYA</Kicker><h2>Siap Mengelola Bisnis<br /><span>dengan Lebih Baik?</span></h2><p>Mulai gunakan NIAGANTARA dan kelola operasional bisnis Anda dalam satu platform.</p><div className="actions"><Button href="mailto:support@niagantara.com">Coba Gratis</Button><Button secondary href="https://niagantara-app.pages.dev">Masuk</Button></div></div></section>
  </main><Footer /></div>;
}

function Heading({ kicker, title, text }: { kicker: string; title: React.ReactNode; text?: string }) { return <div className="heading"><Kicker>{kicker}</Kicker><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Kicker({ children }: { children: React.ReactNode }) { return <div className="kicker">{children}</div>; }
function Metric({ icon, name, value, change }: { icon: string; name: string; value: string; change: string }) { return <div className="metric"><Icon>{icon}</Icon><small>{name}</small><b>{value}</b><em>{change}</em></div>; }
function Price({ name, title, text, featured = false }: { name: string; title: string; text: string; featured?: boolean }) { return <div className={`price${featured?' featured':''}`}>{featured && <strong>REKOMENDASI</strong>}<small>{name}</small><h3>{title}</h3><b>Segera hadir</b><p>{text}</p><a href="#kontak">Beri tahu saya <span>→</span></a></div>; }
function Footer() { return <footer className="footer"><div className="container footer-grid"><div><BrandLogo /><p>Platform untuk mengelola operasional bisnis Anda dengan lebih terhubung.</p><small>© 2026 NIAGANTARA. All rights reserved.</small></div><div><h4>Produk</h4><a href="#solusi">POS</a><a href="#solusi">Inventory</a><a href="#harga">Keuangan</a><a href="#showcase">Laporan</a><a href="#kontak">Google Sheets</a></div><div><h4>Perusahaan</h4><a href="#tentang">Tentang</a><a href="mailto:support@niagantara.com">Kontak</a></div><div><h4>Bantuan</h4><a href="#faq">FAQ</a><a href="mailto:support@niagantara.com">Pusat Bantuan</a></div><div><h4>Legal</h4><a href="/privacy">Kebijakan Privasi</a><a href="/terms">Syarat & Ketentuan</a></div></div></footer>; }
function Legal({ title, children }: { title: string; children: React.ReactNode }) { return <main className="legal"><div className="container"><BrandLogo /><a className="back" href="/">← Kembali ke beranda</a><h1>{title}</h1>{children}</div></main>; }
function Privacy() { return <Legal title="Kebijakan Privasi"><p>Terakhir diperbarui: 22 August 2026</p><h2>Informasi yang kami proses</h2><p>NIAGANTARA memproses identitas akun, catatan autentikasi, keanggotaan perusahaan dan cabang, serta data bisnis yang dimasukkan oleh pengguna berwenang.</p><h2>Integrasi Google</h2><p>Saat administrator menghubungkan Google, NIAGANTARA meminta identitas email dan akses Google Sheets yang diperlukan untuk pelaporan. Token refresh dienkripsi dan tidak ditampilkan kepada browser.</p><h2>Penyimpanan dan keamanan</h2><p>Supabase adalah sumber data utama. Google Sheets adalah lapisan pelaporan. Log operasional, security events, dan audit records mendukung operasi dan keamanan.</p><h2>Kontak</h2><p>Permintaan privasi: <a href="mailto:privacy@niagantara.com">privacy@niagantara.com</a>.</p></Legal>; }
function Terms() { return <Legal title="Syarat & Ketentuan"><p>Terakhir diperbarui: 22 August 2026</p><h2>Akun dan penggunaan</h2><p>Anda bertanggung jawab memberikan informasi yang akurat, menjaga kredensial, dan menggunakan NIAGANTARA secara sah.</p><h2>Data bisnis</h2><p>Anda bertanggung jawab atas akurasi dan hak penggunaan data yang dimasukkan. Catatan Supabase tetap menjadi sumber data utama.</p><h2>Kontak</h2><p>Pertanyaan: <a href="mailto:support@niagantara.com">support@niagantara.com</a>.</p></Legal>; }
const path = window.location.pathname; const Page = path === '/privacy' ? Privacy : path === '/terms' ? Terms : Home; createRoot(document.getElementById('root')!).render(<StrictMode><Page /></StrictMode>);
