import type {
  DemoProduct,
  DemoCategory,
  DemoCustomer,
  DemoSupplier,
  DemoEmployee,
  DemoSale,
  DemoShift,
  DemoPurchase,
  DemoExpense,
  DemoAttendance,
  DemoStockMovement,
  DemoBranch,
  DemoStore,
  DemoWarehouse,
  DemoFinance,
  DemoSheet,
} from './demo-types';

export const demoCompany = 'PT Makmur Nusantara';
export const demoUser = { name: 'Rony Tech', role: 'Owner' };

export const demoStores: DemoStore[] = [
  { id: 'store-1', name: 'Toko Makmur Jaya' },
];

export const demoBranches: DemoBranch[] = [
  {
    id: 'branch-1',
    name: 'Main Branch / Medan',
    code: 'MDN',
    storeId: 'store-1',
  },
  { id: 'branch-2', name: 'Cabang Binjai', code: 'BJI', storeId: 'store-1' },
  {
    id: 'branch-3',
    name: 'Cabang Deli Serdang',
    code: 'DS',
    storeId: 'store-1',
  },
];

export const demoWarehouses: DemoWarehouse[] = [
  {
    id: 'wh-1',
    name: 'Gudang Utama',
    code: 'GU',
    storeId: 'store-1',
    branchId: 'branch-1',
  },
  {
    id: 'wh-2',
    name: 'Gudang Binjai',
    code: 'GB',
    storeId: 'store-1',
    branchId: 'branch-2',
  },
];

export const demoCategories: DemoCategory[] = [
  {
    id: 'cat-1',
    name: 'Sembako',
    description: 'Bahan pokok kebutuhan sehari-hari',
  },
  { id: 'cat-2', name: 'Minuman', description: 'Aneka minuman' },
  { id: 'cat-3', name: 'Snack', description: 'Makanan ringan' },
  { id: 'cat-4', name: 'Perawatan', description: 'Produk perawatan tubuh' },
  {
    id: 'cat-5',
    name: 'Elektronik',
    description: 'Barang elektronik rumah tangga',
  },
];

export const demoProducts: DemoProduct[] = [
  {
    id: 'prod-1',
    name: 'Beras Premium 5kg',
    sku: 'BRP-001',
    category: 'Sembako',
    costPrice: 65000,
    sellingPrice: 82000,
    stock: 125,
    minimumStock: 20,
    barcode: '899100101001',
    unit: 'kg',
    status: 'ACTIVE',
  },
  {
    id: 'prod-2',
    name: 'Minyak Goreng 2L',
    sku: 'MYK-001',
    category: 'Sembako',
    costPrice: 28000,
    sellingPrice: 35000,
    stock: 8,
    minimumStock: 15,
    barcode: '899100101002',
    unit: 'L',
    status: 'ACTIVE',
  },
  {
    id: 'prod-3',
    name: 'Gula Pasir 1kg',
    sku: 'GLA-001',
    category: 'Sembako',
    costPrice: 12000,
    sellingPrice: 15000,
    stock: 200,
    minimumStock: 30,
    barcode: '899100101003',
    unit: 'kg',
    status: 'ACTIVE',
  },
  {
    id: 'prod-4',
    name: 'Tepung Terigu 1kg',
    sku: 'TPG-001',
    category: 'Sembako',
    costPrice: 10000,
    sellingPrice: 13000,
    stock: 150,
    minimumStock: 25,
    barcode: '899100101004',
    unit: 'kg',
    status: 'ACTIVE',
  },
  {
    id: 'prod-5',
    name: 'Telur Ayam 1kg',
    sku: 'TEL-001',
    category: 'Sembako',
    costPrice: 24000,
    sellingPrice: 30000,
    stock: 5,
    minimumStock: 10,
    barcode: '899100101005',
    unit: 'kg',
    status: 'ACTIVE',
  },
  {
    id: 'prod-6',
    name: 'Air Mineral 600ml',
    sku: 'AIR-001',
    category: 'Minuman',
    costPrice: 2500,
    sellingPrice: 3500,
    stock: 500,
    minimumStock: 50,
    barcode: '899100101006',
    unit: 'botol',
    status: 'ACTIVE',
  },
  {
    id: 'prod-7',
    name: 'Teh Botol Sosro 450ml',
    sku: 'TEH-001',
    category: 'Minuman',
    costPrice: 3500,
    sellingPrice: 5000,
    stock: 300,
    minimumStock: 40,
    barcode: '899100101007',
    unit: 'botol',
    status: 'ACTIVE',
  },
  {
    id: 'prod-8',
    name: 'Kopi Sachet',
    sku: 'KOP-001',
    category: 'Minuman',
    costPrice: 800,
    sellingPrice: 1500,
    stock: 1000,
    minimumStock: 100,
    barcode: '899100101008',
    unit: 'sachet',
    status: 'ACTIVE',
  },
  {
    id: 'prod-9',
    name: 'Keripik Singkong',
    sku: 'SNK-001',
    category: 'Snack',
    costPrice: 8000,
    sellingPrice: 12000,
    stock: 80,
    minimumStock: 15,
    barcode: '899100101009',
    unit: 'pack',
    status: 'ACTIVE',
  },
  {
    id: 'prod-10',
    name: 'Biskuit Kaleng',
    sku: 'SNK-002',
    category: 'Snack',
    costPrice: 15000,
    sellingPrice: 22000,
    stock: 45,
    minimumStock: 10,
    barcode: '899100101010',
    unit: 'kaleng',
    status: 'ACTIVE',
  },
  {
    id: 'prod-11',
    name: 'Sabun Mandi Cair',
    sku: 'PRW-001',
    category: 'Perawatan',
    costPrice: 18000,
    sellingPrice: 25000,
    stock: 60,
    minimumStock: 12,
    barcode: '899100101011',
    unit: 'botol',
    status: 'ACTIVE',
  },
  {
    id: 'prod-12',
    name: 'Shampoo Botol',
    sku: 'PRW-002',
    category: 'Perawatan',
    costPrice: 22000,
    sellingPrice: 32000,
    stock: 40,
    minimumStock: 8,
    barcode: '899100101012',
    unit: 'botol',
    status: 'ACTIVE',
  },
];

export const demoCustomers: DemoCustomer[] = [
  {
    id: 'cust-1',
    name: 'Budi Santoso',
    email: 'budi@email.com',
    phone: '081234567890',
    address: 'Jl. Merdeka No. 10, Medan',
    totalPurchases: 2500000,
    lastPurchase: '2024-08-24',
  },
  {
    id: 'cust-2',
    name: 'Siti Rahayu',
    email: 'siti@email.com',
    phone: '081234567891',
    address: 'Jl. Sudirman No. 25, Medan',
    totalPurchases: 1800000,
    lastPurchase: '2024-08-23',
  },
  {
    id: 'cust-3',
    name: 'Ahmad Wijaya',
    email: 'ahmad@email.com',
    phone: '081234567892',
    address: 'Jl. Gatot Subroto No. 15, Medan',
    totalPurchases: 3200000,
    lastPurchase: '2024-08-24',
  },
];

export const demoSuppliers: DemoSupplier[] = [
  {
    id: 'sup-1',
    name: 'PT Beras Jaya',
    email: 'beras@berasjaya.com',
    phone: '061-123456',
    address: 'Jl. Pergudangan No. 5, Medan',
    contactPerson: 'Pak Herman',
  },
  {
    id: 'sup-2',
    name: 'CV Minuman Segar',
    email: 'minuman@minumansegar.com',
    phone: '061-234567',
    address: 'Jl. Industri No. 10, Medan',
    contactPerson: 'Bu Rina',
  },
  {
    id: 'sup-3',
    name: 'UD Snack Berkah',
    email: 'snack@snackberkah.com',
    phone: '061-345678',
    address: 'Jl. Pabrik No. 8, Binjai',
    contactPerson: 'Pak Joko',
  },
];

export const demoEmployees: DemoEmployee[] = [
  {
    id: 'emp-1',
    name: 'Dewi Lestari',
    email: 'dewi@makmurjaya.com',
    phone: '081111111111',
    role: 'Kasir',
    branch: 'Main Branch / Medan',
    status: 'ACTIVE',
  },
  {
    id: 'emp-2',
    name: 'Eko Prasetyo',
    email: 'eko@makmurjaya.com',
    phone: '081111111112',
    role: 'Kasir',
    branch: 'Cabang Binjai',
    status: 'ACTIVE',
  },
  {
    id: 'emp-3',
    name: 'Fitri Handayani',
    email: 'fitri@makmurjaya.com',
    phone: '081111111113',
    role: 'Gudang',
    branch: 'Main Branch / Medan',
    status: 'ACTIVE',
  },
];

export const demoSales: DemoSale[] = [
  {
    id: 'sale-1',
    invoice: 'INV-2024-08-24-001',
    date: '2024-08-24',
    customer: 'Budi Santoso',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    total: 485000,
    payment: 'CASH',
    status: 'PAID',
    items: 5,
  },
  {
    id: 'sale-2',
    invoice: 'INV-2024-08-24-002',
    date: '2024-08-24',
    customer: 'Siti Rahayu',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    total: 320000,
    payment: 'QRIS',
    status: 'PAID',
    items: 3,
  },
  {
    id: 'sale-3',
    invoice: 'INV-2024-08-24-003',
    date: '2024-08-24',
    customer: 'Ahmad Wijaya',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    total: 750000,
    payment: 'TRANSFER',
    status: 'PAID',
    items: 8,
  },
  {
    id: 'sale-4',
    invoice: 'INV-2024-08-23-001',
    date: '2024-08-23',
    customer: 'Budi Santoso',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    total: 520000,
    payment: 'CASH',
    status: 'PAID',
    items: 6,
  },
  {
    id: 'sale-5',
    invoice: 'INV-2024-08-23-002',
    date: '2024-08-23',
    customer: 'Siti Rahayu',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    total: 280000,
    payment: 'QRIS',
    status: 'PAID',
    items: 4,
  },
];

export const demoShifts: DemoShift[] = [
  {
    id: 'shift-1',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    openingTime: '2024-08-24T08:00:00',
    closingTime: '2024-08-24T17:00:00',
    openingCash: 500000,
    expectedCash: 2055000,
    closingCash: 2055000,
    difference: 0,
    status: 'CLOSED',
  },
  {
    id: 'shift-2',
    cashier: 'Dewi Lestari',
    branch: 'Main Branch / Medan',
    openingTime: '2024-08-25T08:00:00',
    openingCash: 500000,
    expectedCash: 500000,
    status: 'OPEN',
  },
];

export const demoPurchases: DemoPurchase[] = [
  {
    id: 'pur-1',
    invoice: 'PO-2024-08-20-001',
    date: '2024-08-20',
    supplier: 'PT Beras Jaya',
    branch: 'Main Branch / Medan',
    total: 2500000,
    status: 'RECEIVED',
    items: 20,
  },
  {
    id: 'pur-2',
    invoice: 'PO-2024-08-22-001',
    date: '2024-08-22',
    supplier: 'CV Minuman Segar',
    branch: 'Main Branch / Medan',
    total: 1800000,
    status: 'RECEIVED',
    items: 15,
  },
  {
    id: 'pur-3',
    invoice: 'PO-2024-08-25-001',
    date: '2024-08-25',
    supplier: 'UD Snack Berkah',
    branch: 'Main Branch / Medan',
    total: 1200000,
    status: 'PENDING',
    items: 10,
  },
];

export const demoExpenses: DemoExpense[] = [
  {
    id: 'exp-1',
    category: 'Listrik',
    amount: 1500000,
    date: '2024-08-01',
    branch: 'Main Branch / Medan',
    description: 'Tagihan listrik bulan Juli',
  },
  {
    id: 'exp-2',
    category: 'Transportasi',
    amount: 250000,
    date: '2024-08-15',
    branch: 'Main Branch / Medan',
    description: 'Bensin operasional',
  },
  {
    id: 'exp-3',
    category: 'ATK',
    amount: 150000,
    date: '2024-08-20',
    branch: 'Main Branch / Medan',
    description: 'Pembelian kertas dan printer',
  },
];

export const demoAttendance: DemoAttendance[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'Dewi Lestari',
    date: '2024-08-24',
    clockIn: '08:00',
    clockOut: '17:00',
    branch: 'Main Branch / Medan',
    status: 'PRESENT',
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'Eko Prasetyo',
    date: '2024-08-24',
    clockIn: '08:15',
    clockOut: '17:00',
    branch: 'Cabang Binjai',
    status: 'LATE',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'Fitri Handayani',
    date: '2024-08-24',
    clockIn: '08:00',
    clockOut: '17:00',
    branch: 'Main Branch / Medan',
    status: 'PRESENT',
  },
];

export const demoStockMovements: DemoStockMovement[] = [
  {
    id: 'mov-1',
    productId: 'prod-1',
    productName: 'Beras Premium 5kg',
    type: 'PURCHASE',
    quantity: 50,
    branch: 'Main Branch / Medan',
    date: '2024-08-20',
    reason: 'Stok masuk dari supplier',
  },
  {
    id: 'mov-2',
    productId: 'prod-2',
    productName: 'Minyak Goreng 2L',
    type: 'SALE',
    quantity: -2,
    branch: 'Main Branch / Medan',
    date: '2024-08-24',
    reason: 'Penjualan POS',
  },
  {
    id: 'mov-3',
    productId: 'prod-5',
    productName: 'Telur Ayam 1kg',
    type: 'ADJUSTMENT',
    quantity: -5,
    branch: 'Main Branch / Medan',
    date: '2024-08-24',
    reason: 'Penyesuaian stok rusak',
  },
];

export const demoFinance: DemoFinance = {
  cash: 8500000,
  bank: 12500000,
  receivable: 2500000,
  payable: 3200000,
  expense: 8500000,
  revenue: 12842000,
  profit: 4286000,
};

export const demoSheet: DemoSheet = {
  name: 'Q3_Business_Report',
  headers: ['Tanggal', 'Penjualan', 'Laba', 'Cabang'],
  cells: [
    { row: 0, col: 0, value: '22 Agu' },
    { row: 0, col: 1, value: 'Rp 8.420.000' },
    { row: 0, col: 2, value: 'Rp 2.840.000' },
    { row: 0, col: 3, value: 'Toko Pusat' },
    { row: 1, col: 0, value: '21 Agu' },
    { row: 1, col: 1, value: 'Rp 7.980.000' },
    { row: 1, col: 2, value: 'Rp 2.510.000' },
    { row: 1, col: 3, value: 'Selatan' },
    { row: 2, col: 0, value: '20 Agu' },
    { row: 2, col: 1, value: 'Rp 9.120.000' },
    { row: 2, col: 2, value: 'Rp 3.150.000' },
    { row: 2, col: 3, value: 'Toko Pusat' },
  ],
};

export const demoDashboardMetrics = {
  todaySales: 4850000,
  todayProfit: 1250000,
  todayTransactions: 32,
  lowStockCount: 12,
  productsSold: 120,
};
