import{createDecipheriv,createHash}from'node:crypto';import{createClient,type SupabaseClient}from'@supabase/supabase-js';
export function safeSheetValue(value:unknown):string|number|boolean{if(typeof value==='number')return Number.isFinite(value)?value:'';if(typeof value==='boolean')return value;if(value==null)return'';const s=String(value).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'');return/^[=+\-@]/.test(s)?`'${s}`:s}
export function retryDelayMs(attempt:number,random=Math.random()){const base=Math.min(15*60_000,1000*2**Math.max(0,attempt-1));return Math.round(base*(.75+random*.5))}
function decryptToken(value:string,secret:string){const[v,iv,tag,data]=value.split('.');if(v!=='v1'||!iv||!tag||!data||secret.length<32)throw new Error('INVALID_ENCRYPTED_TOKEN');const d=createDecipheriv('aes-256-gcm',createHash('sha256').update(secret).digest(),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}
type Env={url:string;key:string;clientId:string;clientSecret:string;encryptionKey:string;workerId:string;googleTimeoutMs:number;rebuildPageSize:number};
export function workerEnvironment(source=process.env):Env{const names=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_TOKEN_ENCRYPTION_KEY']as const;for(const n of names)if(!source[n]?.trim())throw new Error(`${n} is required.`);if(source.GOOGLE_TOKEN_ENCRYPTION_KEY!.trim().length<32)throw new Error('GOOGLE_TOKEN_ENCRYPTION_KEY must contain at least 32 characters.');const timeout=Number(source.GOOGLE_API_TIMEOUT_MS||15000),pageSize=Number(source.SHEET_REBUILD_PAGE_SIZE||500);if(!Number.isInteger(timeout)||timeout<1000||timeout>60000)throw new Error('GOOGLE_API_TIMEOUT_MS must be between 1000 and 60000.');if(!Number.isInteger(pageSize)||pageSize<10||pageSize>1000)throw new Error('SHEET_REBUILD_PAGE_SIZE must be between 10 and 1000.');return{url:source.SUPABASE_URL!,key:source.SUPABASE_SERVICE_ROLE_KEY!,clientId:source.GOOGLE_CLIENT_ID!,clientSecret:source.GOOGLE_CLIENT_SECRET!,encryptionKey:source.GOOGLE_TOKEN_ENCRYPTION_KEY!,workerId:source.WORKER_ID?.trim()||`sheets-${process.pid}`,googleTimeoutMs:timeout,rebuildPageSize:pageSize}}
export class SheetSyncWorker{constructor(private db:SupabaseClient,private env:Env,private fetcher:typeof fetch=fetch){}
 async runOnce(batch=20){const{data,error}=await this.db.rpc('claim_sheet_sync_jobs',{worker_name:this.env.workerId,batch_size:batch});if(error)throw error;for(const job of data??[])await this.process(job);return(data??[]).length}
 private async process(job:any){const started=new Date().toISOString();try{if(job.dataset==='rebuild'){await this.expandRebuild(job);await this.success(job,started,0);return}const[{data:connection},{data:workbook},{data:def}]=await Promise.all([this.db.from('google_connections').select('*').eq('company_id',job.company_id).eq('status','active').single(),this.db.from('sheet_workbooks').select('*').eq('company_id',job.company_id).eq('status','active').single(),this.db.from('sheet_definitions').select('*,columns:sheet_columns(*)').eq('company_id',job.company_id).eq('dataset',job.dataset).eq('status','active').single()]);if(!connection||!workbook||!def){await this.success(job,started,0,'skipped');return}const record=await this.sourceRecord(job);if(!record){await this.success(job,started,0,'skipped');return}const access=await this.accessToken(decryptToken(connection.encrypted_refresh_token,this.env.encryptionKey));const title=def.monthly?`${def.title} ${this.recordDate(record).slice(0,7)}`:def.title;const columns=(def.columns??[]).filter((c:any)=>c.status==='active').sort((a:any,b:any)=>a.position-b.position);const created=await this.ensureSheet(access,workbook.spreadsheet_id,title);if(created)await this.append(access,workbook.spreadsheet_id,title,[['_sync_key',...columns.map((c:any)=>safeSheetValue(c.label))]]);const keys:any=await this.google(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(workbook.spreadsheet_id)}/values/${encodeURIComponent(`'${title.replaceAll("'","''")}'!A:A`)}`,access);if((keys.values??[]).some((r:any[])=>r[0]===job.source_event_key)){await this.success(job,started,0,'skipped');return}const row=[job.source_event_key,...columns.map((c:any)=>c.data_type==='formula'?c.formula_template:safeSheetValue(record[c.column_key]))];await this.append(access,workbook.spreadsheet_id,title,[row]);await this.success(job,started,1)}catch(e:any){await this.failure(job,started,e)}}
 private async sourceRecord(job:any){let q:any;if(job.dataset==='sales')q=this.db.from('sales').select('*,items:sale_items(*)').eq('company_id',job.company_id);else if(job.dataset==='inventory')q=this.db.from('inventory').select('*,product:products(sku,name),warehouse:warehouses(name)').eq('company_id',job.company_id);else if(job.dataset==='purchases')q=this.db.from('purchases').select('*,supplier:suppliers(name)').eq('company_id',job.company_id);else q=this.db.from('financial_transactions').select('*').eq('company_id',job.company_id);const{data,error}=await q.eq('id',job.source_id).maybeSingle();if(error)throw error;if(data?.product){data.sku=data.product.sku;data.product_name=data.product.name;data.warehouse_name=data.warehouse?.name}if(data?.supplier)data.supplier_name=data.supplier.name;return data}
 private recordDate(r:any){return String(r.completed_at||r.updated_at||r.purchase_date||r.occurred_at||r.created_at||new Date().toISOString())}
 private async expandRebuild(job:any){for(const[dataset,table]of Object.entries({sales:'sales',inventory:'inventory',purchases:'purchases',finance:'financial_transactions'})){for(let from=0;;from+=this.env.rebuildPageSize){const{data,error}=await this.db.from(table).select('id').eq('company_id',job.company_id).order('id').range(from,from+this.env.rebuildPageSize-1);if(error)throw error;for(const row of data??[])await this.db.from('sheet_sync_queue').upsert({company_id:job.company_id,dataset,source_table:table,source_id:row.id,source_event_key:`${job.source_event_key}:${dataset}:${row.id}`},{onConflict:'company_id,source_event_key',ignoreDuplicates:true});if((data??[]).length<this.env.rebuildPageSize)break;}}}
 private async accessToken(refresh:string){const r=await this.fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:refresh,client_id:this.env.clientId,client_secret:this.env.clientSecret,grant_type:'refresh_token'}),signal:AbortSignal.timeout(this.env.googleTimeoutMs)});const b:any=await r.json();if(!r.ok)throw Object.assign(new Error('GOOGLE_TOKEN_REFRESH_FAILED'),{status:r.status,code:b.error});return b.access_token as string}
 private async ensureSheet(token:string,id:string,title:string){const meta:any=await this.google(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=sheets.properties.title`,token);if(meta.sheets?.some((s:any)=>s.properties?.title===title))return false;await this.google(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}:batchUpdate`,token,{method:'POST',body:JSON.stringify({requests:[{addSheet:{properties:{title}}}]})});return true}
 private append(token:string,id:string,title:string,values:(string|number|boolean)[][]){return this.google(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(`'${title.replaceAll("'","''")}'!A:ZZ`)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,token,{method:'POST',body:JSON.stringify({values})})}
 private async google(url:string,token:string,init:RequestInit={}){const r=await this.fetcher(url,{...init,signal:init.signal??AbortSignal.timeout(this.env.googleTimeoutMs),headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...init.headers}});const b:any=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(b.error?.message||'GOOGLE_API_FAILED'),{status:r.status,code:b.error?.status||`GOOGLE_HTTP_${r.status}`,retryable:[408,429,500,502,503,504].includes(r.status)});return b}
 private async success(j:any,started:string,rows:number,outcome='success'){await this.db.from('sheet_sync_queue').update({status:'completed',completed_at:new Date().toISOString(),locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq('id',j.id).eq('company_id',j.company_id);await this.db.from('sheet_sync_history').insert({company_id:j.company_id,queue_id:j.id,dataset:j.dataset,source_event_key:j.source_event_key,outcome,attempt:j.attempts,rows_written:rows,started_at:started})}
 private async failure(j:any,started:string,e:any){const retryable=e.retryable!==false&&j.attempts<j.max_attempts;const status=retryable?'retry':'dead';const code=String(e.code||'SYNC_FAILED').slice(0,120),message=String(e.message||e).slice(0,500);await this.db.from('sheet_sync_queue').update({status,available_at:new Date(Date.now()+retryDelayMs(j.attempts)).toISOString(),locked_at:null,locked_by:null,last_error_code:code,last_error_message:message,updated_at:new Date().toISOString()}).eq('id',j.id).eq('company_id',j.company_id);await this.db.from('sheet_sync_history').insert({company_id:j.company_id,queue_id:j.id,dataset:j.dataset,source_event_key:j.source_event_key,outcome:retryable?'retry':'failed',attempt:j.attempts,error_code:code,error_message:message,started_at:started})}
}
export function createWorker(source=process.env){const env=workerEnvironment(source);return new SheetSyncWorker(createClient(env.url,env.key,{auth:{persistSession:false,autoRefreshToken:false}}),env)}
