name: niagantara_mobile
description: NIAGANTARA mobile — POS, inventory, finance & operations for your business.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  fl_chart: ^0.68.0
  mobile_scanner: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/branding/niagantara-mark.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/branding/niagantara-mark.png'
  remove_alpha_ios: true

flutter_native_splash:
  color: '#0B1220'
  color_dark: '#0B1220'
  image: 'assets/branding/niagantara-logo.png'
  android_12:
    color: '#0B1220'
    image: 'assets/branding/niagantara-mark.png'
